modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="liquidglassmc"
version="1.0.0"
displayName="LiquidGlassMC"
authors="RedxAx And Okil6"
logoFile="assets/reglass/icon.png"
description='''
Liquid Glass Implemented On Your Favorite Pixelated And Cubic Game.
'''

[[dependencies.liquidglassmc]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.0,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.liquidglassmc]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="CLIENT"
